#!/bin/sh

#
# Copyright (c) 2021 JC Cormier
# All rights reserved.
# SPDX-License-Identifier: MIT
# For full license text, see LICENSE file in the repo root or https://opensource.org/licenses/MIT
#

DOTFILES_REPO=https://github.com/jccormier/dotfiles.git
DOTFILES_REPO_SSH=git@github.com:jccormier/dotfiles.git

DOTFILES_HOME=$HOME/.dotfiles

[[ -e "$DOTFILES_HOME" ]] && echo "ERROR: $DOTFILES_HOME already exists, aborting installation" && exit 1

if ! command -v brew >/dev/null 2>&1; then
    echo
    echo "Installing Homebrew..."
    echo 
    echo "you may be prompted for your sudo password"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! command -v ansible >/dev/null 2>&1; then
    echo
    echo "Installing Ansible..."

    brew install ansible
fi

echo
echo "Cloning '$DOTFILES_REPO'..."

mkdir -p $DOTFILES_HOME
git clone $DOTFILES_REPO $DOTFILES_HOME
cd $DOTFILES_HOME
git remote remove origin
git remote add origin $DOTFILES_REPO_SSH

echo
echo "To complete the installation, execute the following:"
echo
echo "  \$ cd $DOTFILES_HOME"
echo "  \$ ./playbook.yml"
echo
 
