#!/bin/sh

#
# Copyright (c) 2021 JC Cormier
# All rights reserved.
# SPDX-License-Identifier: MIT
# For full license text, see LICENSE file in the repo root or https://opensource.org/licenses/MIT
#

DOTFILES_HOME=`dirname $(readlink -f ${0})`

for d in $(du $DOTFILES_HOME/files | awk '{print $2}'); do
    if [[ -d $d ]]; then
        target=$HOME$(echo $d | sed s:$DOTFILES_HOME/files::g)
        
        mkdir -p $HOME$(echo $d | sed s:$DOTFILES_HOME/files::g)
    fi
done

for f in $(du -a $DOTFILES_HOME/files | awk '{print $2}'); do
    if [[ -f $f ]]; then 
        target=$HOME$(echo $f | sed s:$DOTFILES_HOME/files::g)
        
        if [[ -f $target ]]; then
            if [[ -L $target ]]; then
                echo "Removing symlink $target"
                rm $target
            else
                echo "Backing up $target to $target.old"
                mv $target $target.old
            fi
        fi
        
        ln -s $f $target
    fi
done
